#!/usr/bin/env python

# This script is used to parse data dump files generated by
# 'stream_parser' tool form https://github.com/twindb/undrop-for-innodb

import glob
import gzip
import binascii
from io import BytesIO

def parse_file(input_file):
    with open(input_file, 'r') as file:
        lines = file.readlines()

    for line in lines:
        columns = line.split('\t')

        if len(columns) < 5:
            continue

        rowid = columns[2]
        hexstr = columns[3]
        flags = columns[4]

        if rowid == "NULL":
            rowid = hexstr[0:8]

        if hexstr == None or hexstr == "" or hexstr == "NULL":
            continue

        data = binascii.unhexlify(hexstr)
        try:
            with gzip.GzipFile(fileobj=BytesIO(data)) as gz:
                text = gz.read().decode('utf-8')
        except Exception as ex:
            pass

        try:
            text = data.decode('latin-1', errors='replace')
        except Exception as ex:
            try:
                text = data.decode('utf-8', errors='replace')
            except Exception as ex:
                continue

        outfile = 'out/{}'.format(rowid)
        print(outfile)
        with open(outfile, 'w') as file:
            file.writelines(text)

for file in glob.glob('scan/*.data'):
    print(file)
    parse_file(file)
